const express = require("express")
const app = express()
const cookieParser = require("cookie-parser")
const postRouter = require("./routes/post.js")
const authRoutes = require("./routes/auth")
const cors = require("cors")
app.use(cors())
app.use(express.json())
app.use("/posts", postRouter)
app.use("/" , authRoutes)
app.listen(5000, () => {
    console.log("Listening on port 5000")
})